apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bdmonedas-sfs-tt
spec:
  serviceName: "bdmonedas-servicio"
  replicas: 1
  selector:
    matchLabels:
      app: bdmonedas 
  template:
    metadata:
      labels:
        app: bdmonedas
    spec:
      containers:
        - name: bdmonedas
          image: postgres:16
          ports:
          - containerPort: 5445
          env:
          - name: POSTGRES_DB
            value: monedas
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bdmonedas-secretos-tt
                key: BDMONEDAS_PASSWORD
          volumeMounts:
            - name: storage-bdmonedas
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: storage-bdmonedas
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

            
