apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimonedas-deployment-tt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apimonedas-tt
  template:
    metadata:
      labels:
        app: apimonedas-tt
    spec:
      containers:
        - name: apimonedas
          image: sarazapatasaldarriaga/apimonedas-tt:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: apimonedas-cm-tt
            - secretRef:
                name: bdmonedas-secretos-tt
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bdmonedas-secretos-tt
                  key: BDMONEDAS_PASSWORD
