apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apimonedas-hpa-tt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apimonedas-deployment-tt
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50