apiVersion: batch/v1
kind: Job
metadata:
  name: iniciar-bdmonedas-tt
  spec:
  restartPolicy: Never
  containers:
  - name: iniciar-bdmonedas
    image: postgres:16
    command: ["/bin/bash", "-c"]
    args:
    - |
      